### ISSUE TITLE
Use IP from "kubectl get nodes -o wide" command output to make it clear this is from one of the node 

### ISSUE THREAD

**Issue by izugbokwe** [liwenwu-amazon/reinvent2018-NET410#10]
vethxx interfaces are for pods that are running in kube-system name space:
$: kubectl get pods -o wide --all-namespaces |grep 10-1-2-179
kube-system   kube-dns-5fbcb4d67b-hr4vr                                         3/3     Running   0          18h   100.65.129.4   ip-10-1-2-179.us-west-2.compute.internal
kube-system   kube-dns-autoscaler-6874c546dd-k2twt                              1/1     Running   0          2d    100.65.129.2   ip-10-1-2-179.us-west-2.compute.internal
kube-system   kube-proxy-ip-10-1-2-179.us-west-2.compute.internal               1/1     Running   0          2d    10.1.2.179     ip-10-1-2-179.us-west-2.compute.internal
kube-system   kubernetes-dashboard-7b9c7bc8c9-ttc7z                             1/1     Running   0          2d    100.65.129.3   ip-10-1-2-179.us-west-2.compute.internal
$:

**Comment by pm010537** [comment]
added your suggestion. Will push the change
