### ISSUE TITLE
We need to show how eni id was obtained -aws ec2 describe-network-interfaces --network-interface-ids eni-0f96810f42e4f53e8 --region eu-west-1

### ISSUE THREAD

**Issue by izugbokwe** [liwenwu-amazon/reinvent2018-NET410#30]
aws ec2 describe-network-interfaces --network-interface-ids eni-0f96810f42e4f53e8 --region eu-west-1

**Comment by liwenwu-amazon** [comment]
Have added few words on it. Please reopen it if it is not clear
